kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  environment:
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: manifest/Dockerfile 
    tag: ${DRONE_TAG#manifest-}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/drone-prime-manifest
  when:
   ref:
   - refs/tags/manifest-v*
   instance:
     include:
     - drone-publish.rancher.io
   event:
   - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: publish-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: publish-amd64
  image: plugins/docker
  environment:
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: publish/Dockerfile.amd64 
    tag: ${DRONE_TAG#publish-}-linux-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/drone-prime-publish
  when:
   ref:
   - refs/tags/publish-v*
   instance:
     include:
     - drone-publish.rancher.io
   event:
   - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: publish-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: publish-arm64
  image: plugins/docker
  environment:
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: publish/Dockerfile.arm64 
    tag: ${DRONE_TAG#publish-}-linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/drone-prime-publish
  when:
   ref:
   - refs/tags/publish-v*
   instance:
     include:
     - drone-publish.rancher.io
   event:
   - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: publish-s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
- name: publish-s390x
  image: rancher/drone-images:docker-s390x
  environment:
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: publish/Dockerfile.s390x 
    tag: ${DRONE_TAG#publish-}-linux-s390x
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/drone-prime-publish
  when:
   ref:
   - refs/tags/publish-v*
   instance:
     include:
     - drone-publish.rancher.io
   event:
   - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: publish-manifest

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
   ref:
   - refs/tags/publish-v*
   instance:
     include:
     - drone-publish.rancher.io
   event:
   - tag

depends_on:
- publish-amd64 
- publish-arm64
- publish-s390x

volumes:
- name: docker
  host:
    path: /var/run/docker.sock