---
kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: publish-amd64
  image: plugins/docker
  environment:
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: Docker/Dockerfile.amd64 
    tag: ${DRONE_TAG}-linux-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: luistt/drone-prime-publish
  when:
	  ref:
	    include:
	      - refs/tags/publish-v*
    instance:
      include:
      - drone-publish.rancher.io
    event:
    #- push
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: build-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: publish-arm64
  image: plugins/docker
  environment:
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: Docker/Dockerfile.arm64 
    tag: ${DRONE_TAG}-linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: luistt/drone-prime-publish
  when:
  	ref:
    	include:
      	- refs/tags/publish-v*
    instance:
      include:
      - drone-publish.rancher.io
    event:
    #- push
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: build-windows-amd64-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: publish-windows-1809-amd64
  image: plugins/docker:windows-1809-amd64
  environment:
  volumes:
  - name: docker
    path: \\\\.\\pipe\\docker_engine
  settings:
    dockerfile: Docker/Dockerfile.windows.amd64.1809
    tag: ${DRONE_TAG}-windows-1809-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: luistt/drone-prime-publish
  when:
  	ref:
    	include:
      	- refs/tags/publish-v*
    instance:
      include:
      - drone-publish.rancher.io
    event:
    #- push
    - tag

volumes:
- name: docker
  host:
    path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: manifest

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
  	ref:
    	include:
      	- refs/tags/publish-v*
    instance:
      include:
      - drone-publish.rancher.io
    event:
    - tag

depends_on:
- build-amd64 
- build-arm64
- build-windows-amd64-1809

volumes:
- name: docker
  host:
    path: /var/run/docker.sock